framework: mocha
postMerge:
  pattern: 
    - "./test/locale/*.js"
preMerge:
  pattern:
    - "./test/locale/*.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 1.0